{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose-molecule/1.8.3/precompose-molecule-1.8.3.module",
    "group": "moe.tlaster",
    "module": "precompose-molecule",
    "version": "1.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-macosArm64Main-1.8.3.klib",
          "url": "precompose-molecule-macosarm64-1.8.3.klib",
          "size": 18431,
          "sha512": "e893a08c8f751c72ffc7f4c217a7c5a923f14482a1e84dbf572e1d63ff3473e64b77ea3b30c6b03c7757a1719904c2c2b7d1c5bf91aa2b452bda3b4b7aeb7ba9",
          "sha256": "7ac21b3cddcc7cad73c874f0df28a7e75cf03eb819a8f26079b1fbcbb02c8c8b",
          "sha1": "fd0f8fe44cbe4b5b1b42200330722366f1c60ad5",
          "md5": "8a2422b2c79b3f20e850f96cb198fad0"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "precompose-molecule-macosarm64-1.8.3-sources.jar",
          "url": "precompose-molecule-macosarm64-1.8.3-sources.jar",
          "size": 3469,
          "sha512": "aca07b6417e8b1b029fff36f05453ca65dced399d9f9b0452ad5ac2c33ccb1f8a5f6e217bf9a04fe219e75752131da37c3fefd0700765ea2e207d2890576a8ce",
          "sha256": "9ac13d7c7809e345e88feb9cd3dfd385eed7aa23421737693b8de81919e5e969",
          "sha1": "e40f1245c596e3d9befc674d5964425b86b7cced",
          "md5": "88a68a161bda3c23ad0bb7a2f1a259ce"
        }
      ]
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-1.8.3.kotlin_resources.zip",
          "url": "precompose-molecule-macosarm64-1.8.3-kotlin_resources.kotlin_resources.zip",
          "size": 350,
          "sha512": "3d48534c96bc96b0bbaed075de7737471e02a3f3b71e116d68050a4e91d0b4a3dd9e85db6cd97a1ed83ccbd3f50580771d2601ce747504493a3cb308b72d8127",
          "sha256": "9013d5c77b73151a091c34c7b602c3e73e2ee21081b4b4eceb5edb357edce915",
          "sha1": "7b3c932e005b56f28eb165e44525f26c07f747b6",
          "md5": "d02592bf83cb75607b618e9a0559415b"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-macosarm64-1.8.3-metadata.jar",
          "url": "precompose-molecule-macosarm64-1.8.3-metadata.jar",
          "size": 4915,
          "sha512": "26a1b44ff57cc4f442d6913053edda403ca48301a1dff7256511ed809a54601dad4eba9b5fdfc623c7877e12d4e216628d6978367304c377e1dd630778f848b7",
          "sha256": "24dbee555c326507d46d0ef46f441d4b16b7e4a6352e0c8a7992f9e7998d0329",
          "sha1": "aec7aa0c8d8f2e478d05eeb91fb44eac8b110177",
          "md5": "6286fc775e4001912c330dae5d660d0c"
        }
      ]
    }
  ]
}
