{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose-molecule/1.7.0/precompose-molecule-1.7.0.module",
    "group": "moe.tlaster",
    "module": "precompose-molecule",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule.klib",
          "url": "precompose-molecule-macosx64-1.7.0.klib",
          "size": 18726,
          "sha512": "749045b4fe61c6a0f33e2bb0e405bc8f398838a6ec9c431d476bd83ecac0fe7acaefe1ad319733c0a9640dde4cbf43452dd8f74d426e43dddfb88c7b62a6d324",
          "sha256": "7f950ca8ea7532b45a6cefd40ce9a144e4e97443c0ac661b31aa449003966cd8",
          "sha1": "04e6f5bf91a24c1fed216383eadc95d362c0ca4c",
          "md5": "ebb69589b27e75ca1537afdf8a2eadf2"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "precompose-molecule-macosx64-1.7.0-sources.jar",
          "url": "precompose-molecule-macosx64-1.7.0-sources.jar",
          "size": 3469,
          "sha512": "aca07b6417e8b1b029fff36f05453ca65dced399d9f9b0452ad5ac2c33ccb1f8a5f6e217bf9a04fe219e75752131da37c3fefd0700765ea2e207d2890576a8ce",
          "sha256": "9ac13d7c7809e345e88feb9cd3dfd385eed7aa23421737693b8de81919e5e969",
          "sha1": "e40f1245c596e3d9befc674d5964425b86b7cced",
          "md5": "88a68a161bda3c23ad0bb7a2f1a259ce"
        }
      ]
    },
    {
      "name": "macosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-1.7.0.kotlin_resources.zip",
          "url": "precompose-molecule-macosx64-1.7.0-kotlin_resources.kotlin_resources.zip",
          "size": 350,
          "sha512": "8ff83e96475789390504381b96554e9de31dab8fcfbf6e0036aea79d3e930471c280b45e8524102d2e3780cd68737bccf1e14b30665c507de2d97b94dfcdd9a3",
          "sha256": "c4a4630fd97c719c46c7da93751b7095d22f5206b8f3a6653346f600c285880e",
          "sha1": "ba23bb19030245b8e9a55103123a76d17a05a33c",
          "md5": "3b4f771c02c255407ffd938895a0467b"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-macosx64-1.7.0-metadata.jar",
          "url": "precompose-molecule-macosx64-1.7.0-metadata.jar",
          "size": 4918,
          "sha512": "a0224fd08b1a4b530adf56c8488af38ba6ce0750dde81ddc9ee3869e6eefc5e672d6145c144c094fa68fd090874adfc5918e0c42572c008f1a315cc03ea1c788",
          "sha256": "52541dca0b244a0e997f6834606ca535588db8227c4087806a0c8811edb07cd2",
          "sha1": "51a37999ce0d112993a360279a48c920628e84a0",
          "md5": "9678aab530535255fa0462f4a40d255a"
        }
      ]
    }
  ]
}
