{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose-molecule/1.8.3/precompose-molecule-1.8.3.module",
    "group": "moe.tlaster",
    "module": "precompose-molecule",
    "version": "1.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-jvm-1.8.3.jar",
          "url": "precompose-molecule-jvm-1.8.3.jar",
          "size": 17952,
          "sha512": "db2ff6b323636fd35bf051008e62101c7b22edcd990587e4813b18fa37a38b646bdcb4dc157ffbbdac0fb71ce286bad6c0dc2b03d6bbe766bc4595e4947b35e9",
          "sha256": "ebdd7a8e31a316416e26cb2da8a91d5b0d4f245127f6d6e9e8fac76353f7e97c",
          "sha1": "c759f8f070b23512a816dfa8088a8ba70dbb6115",
          "md5": "b7ea68ff1514e05c6b008bda82b20fa8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-jvm-1.8.3.jar",
          "url": "precompose-molecule-jvm-1.8.3.jar",
          "size": 17952,
          "sha512": "db2ff6b323636fd35bf051008e62101c7b22edcd990587e4813b18fa37a38b646bdcb4dc157ffbbdac0fb71ce286bad6c0dc2b03d6bbe766bc4595e4947b35e9",
          "sha256": "ebdd7a8e31a316416e26cb2da8a91d5b0d4f245127f6d6e9e8fac76353f7e97c",
          "sha1": "c759f8f070b23512a816dfa8088a8ba70dbb6115",
          "md5": "b7ea68ff1514e05c6b008bda82b20fa8"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "precompose-molecule-jvm-1.8.3-sources.jar",
          "url": "precompose-molecule-jvm-1.8.3-sources.jar",
          "size": 3421,
          "sha512": "da05d330c0cef8b23be98164cef19c3568bd5e297d586d91e84a18b15fe5bcc6061cd0c1f1b25ea1e80560ff29295be6fbd5f6395d94d0dd7d2cf5dd39dbc80d",
          "sha256": "9614f75ce1683c07f8ae00572998fd49003c475daddfc14164b14cc5160cab2a",
          "sha1": "45549679f311e8e104e46a1eb597dc74870de4df",
          "md5": "6c35a0f8b7f7f334705b2be4dd477a00"
        }
      ]
    }
  ]
}
