{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose/1.7.0/precompose-1.7.0.module",
    "group": "moe.tlaster",
    "module": "precompose",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-wasm-js-1.7.0.klib",
          "url": "precompose-wasm-js-1.7.0.klib",
          "size": 204747,
          "sha512": "74e802ad6b50ea1305944f0c2f23c6c9cb3ab7d5853110a415dd5a8ada89bb9e4c87e122a9d80a4620e0ffe62ec3c21117d4263e612e267891a1949ae36922fc",
          "sha256": "422de5c50755c47b62bd94f8cb5460ca374bb44b012a795bbb4c5357ab00f002",
          "sha1": "4dab5520826bb53d33a4a51fd0fea0ff9123f079",
          "md5": "7880d045fb6184678059578038ab439c"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-wasm-js-1.7.0.klib",
          "url": "precompose-wasm-js-1.7.0.klib",
          "size": 204747,
          "sha512": "74e802ad6b50ea1305944f0c2f23c6c9cb3ab7d5853110a415dd5a8ada89bb9e4c87e122a9d80a4620e0ffe62ec3c21117d4263e612e267891a1949ae36922fc",
          "sha256": "422de5c50755c47b62bd94f8cb5460ca374bb44b012a795bbb4c5357ab00f002",
          "sha1": "4dab5520826bb53d33a4a51fd0fea0ff9123f079",
          "md5": "7880d045fb6184678059578038ab439c"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "precompose-wasm-js-1.7.0-sources.jar",
          "url": "precompose-wasm-js-1.7.0-sources.jar",
          "size": 36106,
          "sha512": "c8e18a1f3eb0c6741d0ad7a130384c76dceb81330272cac1bbc8e1bb10c3834f3386ec68acfc2df74d4ecc3399663e42f1e1bebff8359e52d2ece00cb7562197",
          "sha256": "f8f07d841817356e77b0254338ac2d5a040e69a5ce977e6ca7d83d3c68371885",
          "sha1": "eb0027956ef4c3d552e60f717af81cbbad2b955a",
          "md5": "82172b5e2a777e066a40dde940319582"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-1.7.0.kotlin_resources.zip",
          "url": "precompose-wasm-js-1.7.0-kotlin_resources.kotlin_resources.zip",
          "size": 332,
          "sha512": "02b6febaa5e5e77e2f96737ad395482cb19cf755cb27e7e7a040c1266828882d0bea6cce1c14a47e5d56705b4fac50c6cfafd5a2bb22955a63f8404c1c418fa6",
          "sha256": "75f9604341a949953d65bb17d35fa17b4c3b1529663898c5efa5ed1bce3aba16",
          "sha1": "c1884cb7fa069b9c2743b09d30deba4911568186",
          "md5": "cf57fa86df7c2db375c874d8bd5c7844"
        }
      ]
    }
  ]
}
