{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose-molecule/1.8.3/precompose-molecule-1.8.3.module",
    "group": "moe.tlaster",
    "module": "precompose-molecule",
    "version": "1.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-macosX64Main-1.8.3.klib",
          "url": "precompose-molecule-macosx64-1.8.3.klib",
          "size": 18415,
          "sha512": "bba9b4169ec60840ef7c8e439fa0ab9752da400279ed609ea43c8692e5233688461f93ff40f9fe28ba284964872fff6069fee9522d92392ec3b4c69f1a6a92d6",
          "sha256": "ebffbeb9f6f9e7fa7ced7a93d7f2622688d83423e936319cd2986d2c3cc57ef1",
          "sha1": "73f51d65318216524c6647bf4f98feda0dee9b2d",
          "md5": "931ca78768f7e1663e7335fa4e1ee9e2"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "precompose-molecule-macosx64-1.8.3-sources.jar",
          "url": "precompose-molecule-macosx64-1.8.3-sources.jar",
          "size": 3469,
          "sha512": "aca07b6417e8b1b029fff36f05453ca65dced399d9f9b0452ad5ac2c33ccb1f8a5f6e217bf9a04fe219e75752131da37c3fefd0700765ea2e207d2890576a8ce",
          "sha256": "9ac13d7c7809e345e88feb9cd3dfd385eed7aa23421737693b8de81919e5e969",
          "sha1": "e40f1245c596e3d9befc674d5964425b86b7cced",
          "md5": "88a68a161bda3c23ad0bb7a2f1a259ce"
        }
      ]
    },
    {
      "name": "macosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-1.8.3.kotlin_resources.zip",
          "url": "precompose-molecule-macosx64-1.8.3-kotlin_resources.kotlin_resources.zip",
          "size": 350,
          "sha512": "3d48534c96bc96b0bbaed075de7737471e02a3f3b71e116d68050a4e91d0b4a3dd9e85db6cd97a1ed83ccbd3f50580771d2601ce747504493a3cb308b72d8127",
          "sha256": "9013d5c77b73151a091c34c7b602c3e73e2ee21081b4b4eceb5edb357edce915",
          "sha1": "7b3c932e005b56f28eb165e44525f26c07f747b6",
          "md5": "d02592bf83cb75607b618e9a0559415b"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-macosx64-1.8.3-metadata.jar",
          "url": "precompose-molecule-macosx64-1.8.3-metadata.jar",
          "size": 4915,
          "sha512": "26a1b44ff57cc4f442d6913053edda403ca48301a1dff7256511ed809a54601dad4eba9b5fdfc623c7877e12d4e216628d6978367304c377e1dd630778f848b7",
          "sha256": "24dbee555c326507d46d0ef46f441d4b16b7e4a6352e0c8a7992f9e7998d0329",
          "sha1": "aec7aa0c8d8f2e478d05eeb91fb44eac8b110177",
          "md5": "6286fc775e4001912c330dae5d660d0c"
        }
      ]
    }
  ]
}
