{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose/1.7.0/precompose-1.7.0.module",
    "group": "moe.tlaster",
    "module": "precompose",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-jvm-1.7.0.jar",
          "url": "precompose-jvm-1.7.0.jar",
          "size": 248582,
          "sha512": "d04f6bfb62cded97385e077637767fc6e9600e3e596a41bab1d98890661f6884cc420d5ba2cef95f44fda9e601e47b62cd0e6e829cbd50cd31ceda13d062e4e6",
          "sha256": "376eccaeab5f3676c8086cc0b0169ea1c3cfe4e2e9447058e6ba148f4dd39c1e",
          "sha1": "1fd845597bd4bd78e68848c60635a40d1c32e132",
          "md5": "070b2d9f1ef2ecbb8c986f7f2254f5d0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-jvm-1.7.0.jar",
          "url": "precompose-jvm-1.7.0.jar",
          "size": 248582,
          "sha512": "d04f6bfb62cded97385e077637767fc6e9600e3e596a41bab1d98890661f6884cc420d5ba2cef95f44fda9e601e47b62cd0e6e829cbd50cd31ceda13d062e4e6",
          "sha256": "376eccaeab5f3676c8086cc0b0169ea1c3cfe4e2e9447058e6ba148f4dd39c1e",
          "sha1": "1fd845597bd4bd78e68848c60635a40d1c32e132",
          "md5": "070b2d9f1ef2ecbb8c986f7f2254f5d0"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "precompose-jvm-1.7.0-sources.jar",
          "url": "precompose-jvm-1.7.0-sources.jar",
          "size": 36409,
          "sha512": "6e36c8a714c6a2a4a81e8aca1418da38ca2c6af09e775eef34a9177fefead75b50d410c622eea404675424973455687e2eb4e93705947818596813e4180c3d2d",
          "sha256": "491b39edb6991b47cae6c249f4edfb550cb2c025a528e186990f0bab13f37982",
          "sha1": "b89bd8ec3b2c947c5e8adc2cad37a9e877da2fe8",
          "md5": "b93365ee3ad1614004fb1dccf36ccc8c"
        }
      ]
    }
  ]
}
