{
  "formatVersion": "1.1",
  "component": {
    "group": "moe.tlaster",
    "module": "precompose-molecule",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-metadata-1.7.0.jar",
          "url": "precompose-molecule-1.7.0.jar",
          "size": 3184,
          "sha512": "e84debff69dddabebd01132c46bb4454e355bdde0cfd4451a9a800b4097e6e3a9dc9fc4ec92a42f52307932bcb8b57ce2eb07b37dbbb1b79f1823fb28213e0eb",
          "sha256": "2fc72f59aa7d8b01b6fb7cf202c350c39713b5c9cdcab945c51d69ae6248ccbb",
          "sha1": "9a10dcab51cabd073145413b5c5ef9575922ffb3",
          "md5": "c544e8d03114a35162800f354fdf911b"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "precompose-molecule-kotlin-1.7.0-sources.jar",
          "url": "precompose-molecule-1.7.0-sources.jar",
          "size": 4447,
          "sha512": "67870407aefa0c0a0f104d8986944f5728bf2ffe7aeaeca7111a06c58816737f0172dd816dffc568270711b1ac1905d91f726225a4e3fb99b30ea110eac83e0c",
          "sha256": "3555203a26a86eec0277bad63396f2c9de53125ae1a15022a6f8b9127a05591c",
          "sha1": "a7684a7de80af7add3e716b95db6f0b1c4bd939f",
          "md5": "c671997ad470b0a601bb6105cdb44d0d"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../precompose-molecule-android-debug/1.7.0/precompose-molecule-android-debug-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-android-debug",
        "version": "1.7.0"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../precompose-molecule-android-debug/1.7.0/precompose-molecule-android-debug-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-android-debug",
        "version": "1.7.0"
      }
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../precompose-molecule-android-debug/1.7.0/precompose-molecule-android-debug-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-android-debug",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../precompose-molecule-android/1.7.0/precompose-molecule-android-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../precompose-molecule-android/1.7.0/precompose-molecule-android-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../precompose-molecule-android/1.7.0/precompose-molecule-android-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-iosarm64/1.7.0/precompose-molecule-iosarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-iosarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-iosarm64/1.7.0/precompose-molecule-iosarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-iosarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-iosarm64/1.7.0/precompose-molecule-iosarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-iosarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-iosarm64/1.7.0/precompose-molecule-iosarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-iosarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-iossimulatorarm64/1.7.0/precompose-molecule-iossimulatorarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-iossimulatorarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-iossimulatorarm64/1.7.0/precompose-molecule-iossimulatorarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-iossimulatorarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-iossimulatorarm64/1.7.0/precompose-molecule-iossimulatorarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-iossimulatorarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-iossimulatorarm64/1.7.0/precompose-molecule-iossimulatorarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-iossimulatorarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-iosx64/1.7.0/precompose-molecule-iosx64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-iosx64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-iosx64/1.7.0/precompose-molecule-iosx64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-iosx64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-iosx64/1.7.0/precompose-molecule-iosx64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-iosx64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-iosx64/1.7.0/precompose-molecule-iosx64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-iosx64",
        "version": "1.7.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../precompose-molecule-js/1.7.0/precompose-molecule-js-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-js",
        "version": "1.7.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../precompose-molecule-js/1.7.0/precompose-molecule-js-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-js",
        "version": "1.7.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../precompose-molecule-js/1.7.0/precompose-molecule-js-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-js",
        "version": "1.7.0"
      }
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../precompose-molecule-js/1.7.0/precompose-molecule-js-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-js",
        "version": "1.7.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../precompose-molecule-jvm/1.7.0/precompose-molecule-jvm-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-jvm",
        "version": "1.7.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../precompose-molecule-jvm/1.7.0/precompose-molecule-jvm-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-jvm",
        "version": "1.7.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../precompose-molecule-jvm/1.7.0/precompose-molecule-jvm-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-jvm",
        "version": "1.7.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-macosarm64/1.7.0/precompose-molecule-macosarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-macosarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-macosarm64/1.7.0/precompose-molecule-macosarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-macosarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-macosarm64/1.7.0/precompose-molecule-macosarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-macosarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-macosarm64/1.7.0/precompose-molecule-macosarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-macosarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-macosx64/1.7.0/precompose-molecule-macosx64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-macosx64",
        "version": "1.7.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-macosx64/1.7.0/precompose-molecule-macosx64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-macosx64",
        "version": "1.7.0"
      }
    },
    {
      "name": "macosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-macosx64/1.7.0/precompose-molecule-macosx64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-macosx64",
        "version": "1.7.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-molecule-macosx64/1.7.0/precompose-molecule-macosx64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-molecule-macosx64",
        "version": "1.7.0"
      }
    }
  ]
}
