{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose-molecule/1.7.0/precompose-molecule-1.7.0.module",
    "group": "moe.tlaster",
    "module": "precompose-molecule",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-js-1.7.0.klib",
          "url": "precompose-molecule-js-1.7.0.klib",
          "size": 3327258,
          "sha512": "08c76de2f5a4b2d9a6dea98c5f97ee58ffc9b54d56beea6c0c104b164cb50a918dbec82c46b91058ab363166e689ade612246c204d2bef240eb78e8befa6f99b",
          "sha256": "80e4941da92ac3f0fcdb96f2f67be0ba0cecb56dee2058eb2764ce460bfbc6ed",
          "sha1": "a3c46fbaa9dd9f0d22710b9a77a48ca085e07320",
          "md5": "ec5153451ea498d365042f7f4b3b5f5b"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-js-1.7.0.klib",
          "url": "precompose-molecule-js-1.7.0.klib",
          "size": 3327258,
          "sha512": "08c76de2f5a4b2d9a6dea98c5f97ee58ffc9b54d56beea6c0c104b164cb50a918dbec82c46b91058ab363166e689ade612246c204d2bef240eb78e8befa6f99b",
          "sha256": "80e4941da92ac3f0fcdb96f2f67be0ba0cecb56dee2058eb2764ce460bfbc6ed",
          "sha1": "a3c46fbaa9dd9f0d22710b9a77a48ca085e07320",
          "md5": "ec5153451ea498d365042f7f4b3b5f5b"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "precompose-molecule-js-1.7.0-sources.jar",
          "url": "precompose-molecule-js-1.7.0-sources.jar",
          "size": 3409,
          "sha512": "e1dfb37012e5ee04aa0f75c32880ef69192c79723cd2c60286d6ba5911fa267b13f376804d5eab22e24f85882f0a0b6ec64faec95015fae44a646b77a48d8ee3",
          "sha256": "9c1c02d114dbb5b24f071bb6c2efff1bedcd15dff08153c4a5496489b7817338",
          "sha1": "4e5de43e4c45c07590eba123a22073b522b83ec5",
          "md5": "e23b4c23873dc6d96484e5d7949f2f90"
        }
      ]
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-1.7.0.kotlin_resources.zip",
          "url": "precompose-molecule-js-1.7.0-kotlin_resources.kotlin_resources.zip",
          "size": 350,
          "sha512": "808036ce5b0ed255183bcde0a8eddf0639ac023ecc4e4a02dac6b042c0946908477b954ac946f7d98a11d654850ec3c842af9515d5e4c9341947f471a013e1f7",
          "sha256": "7d0641bb8019574d273565855569736532348f78bfa8793ba859ad1c492807e4",
          "sha1": "7569a1081b8911a648de56bb77fceb215d4e87e0",
          "md5": "fa03397b0fb5bdc540af74d5e9697421"
        }
      ]
    }
  ]
}
