{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose-molecule/1.7.0/precompose-molecule-1.7.0.module",
    "group": "moe.tlaster",
    "module": "precompose-molecule",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-js-1.7.0.klib",
          "url": "precompose-molecule-js-1.7.0.klib",
          "size": 3327262,
          "sha512": "a88cc8008890065b9e00a5a7bec1ea91f4ecfd52ac129ea1e5d981bcfc82acf9bbc0bbe0b8c2015a49b08ab4fcec6e5b8220c0197ea2f0c093337cf461c5cf0c",
          "sha256": "38125fce7d9b3b106aa968783c68953c4059d4a0476c0cb1d8bdee6136a32951",
          "sha1": "845e2af14fdbb03dcaa46a09224a9d93997ec1c3",
          "md5": "ac6e8bb7053e3f5bf078a2aa16da6e3e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-js-1.7.0.klib",
          "url": "precompose-molecule-js-1.7.0.klib",
          "size": 3327262,
          "sha512": "a88cc8008890065b9e00a5a7bec1ea91f4ecfd52ac129ea1e5d981bcfc82acf9bbc0bbe0b8c2015a49b08ab4fcec6e5b8220c0197ea2f0c093337cf461c5cf0c",
          "sha256": "38125fce7d9b3b106aa968783c68953c4059d4a0476c0cb1d8bdee6136a32951",
          "sha1": "845e2af14fdbb03dcaa46a09224a9d93997ec1c3",
          "md5": "ac6e8bb7053e3f5bf078a2aa16da6e3e"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "precompose-molecule-js-1.7.0-sources.jar",
          "url": "precompose-molecule-js-1.7.0-sources.jar",
          "size": 3409,
          "sha512": "e1dfb37012e5ee04aa0f75c32880ef69192c79723cd2c60286d6ba5911fa267b13f376804d5eab22e24f85882f0a0b6ec64faec95015fae44a646b77a48d8ee3",
          "sha256": "9c1c02d114dbb5b24f071bb6c2efff1bedcd15dff08153c4a5496489b7817338",
          "sha1": "4e5de43e4c45c07590eba123a22073b522b83ec5",
          "md5": "e23b4c23873dc6d96484e5d7949f2f90"
        }
      ]
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-1.7.0.kotlin_resources.zip",
          "url": "precompose-molecule-js-1.7.0-kotlin_resources.kotlin_resources.zip",
          "size": 350,
          "sha512": "0d22e8a6e45a6aca8be78a627404cff486848a260bf1ea42093fbc9e925f902864e742116e5ff2c15f27abbf739b58459cb3daf0ba47a9a64d0fb7beac0b5a89",
          "sha256": "88ea4265be92f02febe8c343d7e39d4919421e5388ab5e398520e165dda5f276",
          "sha1": "ee9ec26d6c77548325e4a161d75e7e6ae7434ab8",
          "md5": "aae7ca64d7e1b683384650249e0eb184"
        }
      ]
    }
  ]
}
