{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose-koin/1.7.0/precompose-koin-1.7.0.module",
    "group": "moe.tlaster",
    "module": "precompose-koin",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose-viewmodel",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin.klib",
          "url": "precompose-koin-iossimulatorarm64-1.7.0.klib",
          "size": 9389,
          "sha512": "8eabcaea246d8b9f153b63f9833f44989175b6c8ce688e66601f31fe29dfb746003ad049cbc9be13850dd75b911b77f219d22a4e911992ffc9022fa76ac02f1a",
          "sha256": "3ea8b003372e4e70bd6f95cd195e6a476b2d44e7c6af456a84cd46eb3febe5d2",
          "sha1": "3f422c5ce25d7c22e724024efd8cc9e03a12e36b",
          "md5": "2a00419fbac6c4e62298fe6f65deb54b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "precompose-koin-iossimulatorarm64-1.7.0-sources.jar",
          "url": "precompose-koin-iossimulatorarm64-1.7.0-sources.jar",
          "size": 1559,
          "sha512": "194d8e9967a4f37928679f4ac73d59a9a2f913cd8834f4f4349b05fc12f11ca76a4946ea4dea31b971ab3c7fb9cdaff86d10c983eb1d689b262ba73f7b3deba6",
          "sha256": "12dbb78fca3a1a7bb05bb06087206fa2829964d4b0b9252bf439f409c45a3e5d",
          "sha1": "70ef88a6f223a3104078dedcc81cf04ddf37ea23",
          "md5": "c43ad676a52f1676a9c2f09640b01986"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose-viewmodel",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin-1.7.0.kotlin_resources.zip",
          "url": "precompose-koin-iossimulatorarm64-1.7.0-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "7454882964089123324ef82b11a7a5f982c1464e7e7a9377c01c81f24f1ae7bda4570ba033d1507cc4b582d0012aec39dd62612f546e130eadb811b3a97112b4",
          "sha256": "27884c67228bef3bec24140f5510ba9a32187865f06194d2a180ee66e5fe0bc3",
          "sha1": "c4f819015f535010d0f689e6f64370da9f816920",
          "md5": "08d53b31886a6fbe4ed59c6d7ff6265c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose-viewmodel",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin-iossimulatorarm64-1.7.0-metadata.jar",
          "url": "precompose-koin-iossimulatorarm64-1.7.0-metadata.jar",
          "size": 261,
          "sha512": "dce984bc2b92775886f5597646d34d6fbb32d065ffff3df9e1deb3159385af7c30c5bdfe8e6700fa406a5ecfa712aafe0706261cb688c957754195a15ae8e079",
          "sha256": "ae7a9bc034700a5f32dbe5b16ac9e352ea2fbef5c2d005925b366a339c4d6d32",
          "sha1": "a83ceeddad660777ddb9def1b231953e89a262c4",
          "md5": "defc96c0cabe3ee07702c8ac82cd8607"
        }
      ]
    }
  ]
}
