{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose-koin/1.8.2/precompose-koin-1.8.2.module",
    "group": "moe.tlaster",
    "module": "precompose-koin",
    "version": "1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose-viewmodel",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin-macosArm64Main-1.8.2.klib",
          "url": "precompose-koin-macosarm64-1.8.2.klib",
          "size": 9009,
          "sha512": "c82ee47eb96dc5069e4eef2e896d96fdf38e7ebb3353edfec890843128ee6cbe71fdd1a0fd9e730c902da9b0cabfef6e42853f50cdb1b96e4c903ac8041d489f",
          "sha256": "d6301cc54fe793d6ca91f0bb0d26aa80803a7aa5c2ba88424956f9e266194a0b",
          "sha1": "3f90424352806b32e8110544a835bebf05143467",
          "md5": "18c4156338085db95981f23a6137b106"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "precompose-koin-macosarm64-1.8.2-sources.jar",
          "url": "precompose-koin-macosarm64-1.8.2-sources.jar",
          "size": 1559,
          "sha512": "194d8e9967a4f37928679f4ac73d59a9a2f913cd8834f4f4349b05fc12f11ca76a4946ea4dea31b971ab3c7fb9cdaff86d10c983eb1d689b262ba73f7b3deba6",
          "sha256": "12dbb78fca3a1a7bb05bb06087206fa2829964d4b0b9252bf439f409c45a3e5d",
          "sha1": "70ef88a6f223a3104078dedcc81cf04ddf37ea23",
          "md5": "c43ad676a52f1676a9c2f09640b01986"
        }
      ]
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose-viewmodel",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin-1.8.2.kotlin_resources.zip",
          "url": "precompose-koin-macosarm64-1.8.2-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "ce4f5f32a700f192450be734a7636345928ace89a19608db410159b9a97953c4f9f2963854573e8f4c80e577814d792d5de212668fca29b4067ed74671d322e2",
          "sha256": "ccbcf3037e97544a56f001574308a55cf0542a2bdde5ed3fa868c46c5eab63bc",
          "sha1": "f5a134145669a3bda655e23cbc19d70b31ba5a3d",
          "md5": "b5c9fd679853dc6ecb3b0dd1beaf6a0e"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose-viewmodel",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin-macosarm64-1.8.2-metadata.jar",
          "url": "precompose-koin-macosarm64-1.8.2-metadata.jar",
          "size": 261,
          "sha512": "c32ef8682ed17b80fb1e1967d109372b724b43f6bf2a179d5d2439778798a75d1fb1414a9841df628797085391423a4424ca4c55e790e4ab8f27c4b1cfa7ce81",
          "sha256": "8cc052a05398b482840330cbfbd001341342c673da86bde3e1bd759fbc14093a",
          "sha1": "b8ee41edb0718201de4ba913ca9c8229520a51f6",
          "md5": "ae1bd3b491dfd95167a5b7796fa94eb9"
        }
      ]
    }
  ]
}
