{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose-koin/1.8.3/precompose-koin-1.8.3.module",
    "group": "moe.tlaster",
    "module": "precompose-koin",
    "version": "1.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose-viewmodel",
          "version": {
            "requires": "1.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin-macosX64Main-1.8.3.klib",
          "url": "precompose-koin-macosx64-1.8.3.klib",
          "size": 8993,
          "sha512": "e2fa38efc04a36cc2fb790531e66421dad95073cbbd3139f1a15a3c14caa874093353aefe83314e8dc6bffb53e8bc68a95ff297ed5fc468167e184e824940a29",
          "sha256": "5728bab87ff041d785e134ca7e837d1099578c6f7183fd0c9a39c3b6f4ccd877",
          "sha1": "6128909af07067a3f6ddea5798101ca4728c027f",
          "md5": "1e3aa482cd2f89453a8bd5c1de37192b"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "precompose-koin-macosx64-1.8.3-sources.jar",
          "url": "precompose-koin-macosx64-1.8.3-sources.jar",
          "size": 1559,
          "sha512": "194d8e9967a4f37928679f4ac73d59a9a2f913cd8834f4f4349b05fc12f11ca76a4946ea4dea31b971ab3c7fb9cdaff86d10c983eb1d689b262ba73f7b3deba6",
          "sha256": "12dbb78fca3a1a7bb05bb06087206fa2829964d4b0b9252bf439f409c45a3e5d",
          "sha1": "70ef88a6f223a3104078dedcc81cf04ddf37ea23",
          "md5": "c43ad676a52f1676a9c2f09640b01986"
        }
      ]
    },
    {
      "name": "macosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose-viewmodel",
          "version": {
            "requires": "1.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin-1.8.3.kotlin_resources.zip",
          "url": "precompose-koin-macosx64-1.8.3-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "ce4f5f32a700f192450be734a7636345928ace89a19608db410159b9a97953c4f9f2963854573e8f4c80e577814d792d5de212668fca29b4067ed74671d322e2",
          "sha256": "ccbcf3037e97544a56f001574308a55cf0542a2bdde5ed3fa868c46c5eab63bc",
          "sha1": "f5a134145669a3bda655e23cbc19d70b31ba5a3d",
          "md5": "b5c9fd679853dc6ecb3b0dd1beaf6a0e"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose-viewmodel",
          "version": {
            "requires": "1.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin-macosx64-1.8.3-metadata.jar",
          "url": "precompose-koin-macosx64-1.8.3-metadata.jar",
          "size": 261,
          "sha512": "2d33c23eee8ffe10e71451c835194248aac33e0c298f915281a425e30490a313f9fc01c3499aaeed695b10ddcb5dc735a0cfa6a196eb2ef714b50cb906343fe4",
          "sha256": "106efad814e983465f276a70031717679cebfa2bfa3f18e4570e42a8ef7adb92",
          "sha1": "3a127c761c4d8032da77ac132f1668a4f8325ace",
          "md5": "8af08bbf401aa6fafbc30c34b1890992"
        }
      ]
    }
  ]
}
