{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose-molecule/1.7.0/precompose-molecule-1.7.0.module",
    "group": "moe.tlaster",
    "module": "precompose-molecule",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule.klib",
          "url": "precompose-molecule-iosarm64-1.7.0.klib",
          "size": 18738,
          "sha512": "b7cf1a8f62d0576f6180be40371ace40b54f3121ff135f9180fc05239aaf76c63506f856caeccc8239e1a372ea73d1166425507a37f03267e9aa38e1b30de5ff",
          "sha256": "6e187e52265f661c3139f99e4d89222a17c6e49122377e99a3f284636c6ed12e",
          "sha1": "630c3da54589ef523fa41b37a9204d58dda52c1a",
          "md5": "1687c0a27ffdb964d2cf52e6dccd038d"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "precompose-molecule-iosarm64-1.7.0-sources.jar",
          "url": "precompose-molecule-iosarm64-1.7.0-sources.jar",
          "size": 3446,
          "sha512": "89e69b64e632b9051bcd94c5e8a7cd85148ee92d32d4ed14a47a6f7779bbdc60a501cb49bab27e889b5928c6d81eb66349dc9faf51408f91cd3b3791b58c6a42",
          "sha256": "4b0baa203b2b965f39ac9333aca0ad2903f1dcf431aeb38901e96fbe1e44c106",
          "sha1": "c0165fa21cfb274ee088144e2aaf1b2fd14c375b",
          "md5": "48e06c3b29df5186f65a85b078c6f6f7"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-1.7.0.kotlin_resources.zip",
          "url": "precompose-molecule-iosarm64-1.7.0-kotlin_resources.kotlin_resources.zip",
          "size": 350,
          "sha512": "8ff83e96475789390504381b96554e9de31dab8fcfbf6e0036aea79d3e930471c280b45e8524102d2e3780cd68737bccf1e14b30665c507de2d97b94dfcdd9a3",
          "sha256": "c4a4630fd97c719c46c7da93751b7095d22f5206b8f3a6653346f600c285880e",
          "sha1": "ba23bb19030245b8e9a55103123a76d17a05a33c",
          "md5": "3b4f771c02c255407ffd938895a0467b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-molecule-iosarm64-1.7.0-metadata.jar",
          "url": "precompose-molecule-iosarm64-1.7.0-metadata.jar",
          "size": 4918,
          "sha512": "a0224fd08b1a4b530adf56c8488af38ba6ce0750dde81ddc9ee3869e6eefc5e672d6145c144c094fa68fd090874adfc5918e0c42572c008f1a315cc03ea1c788",
          "sha256": "52541dca0b244a0e997f6834606ca535588db8227c4087806a0c8811edb07cd2",
          "sha1": "51a37999ce0d112993a360279a48c920628e84a0",
          "md5": "9678aab530535255fa0462f4a40d255a"
        }
      ]
    }
  ]
}
