{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose-koin/1.8.2/precompose-koin-1.8.2.module",
    "group": "moe.tlaster",
    "module": "precompose-koin",
    "version": "1.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin-jvm-1.8.2.jar",
          "url": "precompose-koin-jvm-1.8.2.jar",
          "size": 4576,
          "sha512": "d769923dcd47cef1b82408b567458a28a0d880aac5a7ac53cd8e160c3b5a554f4b04b99231bfa6b59ed0a54645c51bd37dc40cfb6995881ae209a2dfcea13d30",
          "sha256": "22f156804976dcad6ed7fe8350b94b9eab608f3d1930d6bc3d8ae876b666e2b1",
          "sha1": "ed3274f29213ef1b58ebc4141370f046ce24d7c7",
          "md5": "4aca66a88ac09cd31a2ffb73eb2af976"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose-viewmodel",
          "version": {
            "requires": "1.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin-jvm-1.8.2.jar",
          "url": "precompose-koin-jvm-1.8.2.jar",
          "size": 4576,
          "sha512": "d769923dcd47cef1b82408b567458a28a0d880aac5a7ac53cd8e160c3b5a554f4b04b99231bfa6b59ed0a54645c51bd37dc40cfb6995881ae209a2dfcea13d30",
          "sha256": "22f156804976dcad6ed7fe8350b94b9eab608f3d1930d6bc3d8ae876b666e2b1",
          "sha1": "ed3274f29213ef1b58ebc4141370f046ce24d7c7",
          "md5": "4aca66a88ac09cd31a2ffb73eb2af976"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "precompose-koin-jvm-1.8.2-sources.jar",
          "url": "precompose-koin-jvm-1.8.2-sources.jar",
          "size": 1559,
          "sha512": "194d8e9967a4f37928679f4ac73d59a9a2f913cd8834f4f4349b05fc12f11ca76a4946ea4dea31b971ab3c7fb9cdaff86d10c983eb1d689b262ba73f7b3deba6",
          "sha256": "12dbb78fca3a1a7bb05bb06087206fa2829964d4b0b9252bf439f409c45a3e5d",
          "sha1": "70ef88a6f223a3104078dedcc81cf04ddf37ea23",
          "md5": "c43ad676a52f1676a9c2f09640b01986"
        }
      ]
    }
  ]
}
