{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose-koin/1.7.0/precompose-koin-1.7.0.module",
    "group": "moe.tlaster",
    "module": "precompose-koin",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose-viewmodel",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin.klib",
          "url": "precompose-koin-iosarm64-1.7.0.klib",
          "size": 9303,
          "sha512": "de8b45eca708fa2b3150a32006ce209a254f27c8d7eaef8d228cac56fcf814659017ef488c4d985b30e7dd658a436109cc6125ea8bcf97ef0505e6a3242a871e",
          "sha256": "5e0d24e14e3bed773f0333669b3baff953884df47ce6b3a1387125907380e028",
          "sha1": "b30ed4d8681adc7297c31abd1551ad9a16eec649",
          "md5": "bbdf9ea284e880ae1bddbeecaa70297e"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "precompose-koin-iosarm64-1.7.0-sources.jar",
          "url": "precompose-koin-iosarm64-1.7.0-sources.jar",
          "size": 1559,
          "sha512": "194d8e9967a4f37928679f4ac73d59a9a2f913cd8834f4f4349b05fc12f11ca76a4946ea4dea31b971ab3c7fb9cdaff86d10c983eb1d689b262ba73f7b3deba6",
          "sha256": "12dbb78fca3a1a7bb05bb06087206fa2829964d4b0b9252bf439f409c45a3e5d",
          "sha1": "70ef88a6f223a3104078dedcc81cf04ddf37ea23",
          "md5": "c43ad676a52f1676a9c2f09640b01986"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose-viewmodel",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin-1.7.0.kotlin_resources.zip",
          "url": "precompose-koin-iosarm64-1.7.0-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "384d2c376afe05371a2d8668c20c0c793a72a7663b0e2202f4be20e1198304562d2fcc17f32f2e820cebbf36c33735a3f6f61adc5a87700ce1f66b6d6be0af0d",
          "sha256": "5447e8f5c46ba9b044331e50c99538ef7a718163bbccfe509e9a076d36519640",
          "sha1": "1d449c34edb01d2f65eb4e7e7d6fc19575a9a59e",
          "md5": "c2215348eca91f76bfd3292bf526f43f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose-viewmodel",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin-iosarm64-1.7.0-metadata.jar",
          "url": "precompose-koin-iosarm64-1.7.0-metadata.jar",
          "size": 261,
          "sha512": "3d2f0a2c8566727e053f2e3293d05eff10067ddeacffb7bd20880287611efe10637e0c0691ef2b3f7bf5fd5b6ea937e03a41724975061403d0d98a0d1bb043ee",
          "sha256": "f2e012d655117e9949628f197d0d7e09f80418f94f217848941477b2ca63689d",
          "sha1": "2f11dc414a84514e12a13b43c9236ef7c5c08221",
          "md5": "cbc25970e70a0d99e51fcb406f0b8a1c"
        }
      ]
    }
  ]
}
