{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose-viewmodel/1.7.0/precompose-viewmodel-1.7.0.module",
    "group": "moe.tlaster",
    "module": "precompose-viewmodel",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-viewmodel-jvm-1.7.0.jar",
          "url": "precompose-viewmodel-jvm-1.7.0.jar",
          "size": 10562,
          "sha512": "d686b2eb3afe19f0c0e69475964f555a16ce06f2bb8aaf75db8d837248d26c46d106088e054c7f9d7c60e931ab45f1af55cb12579c32a378972959269845f7c3",
          "sha256": "8e175e870fe94b5c786acf46a223fea25037165cf7a71d62f7ea90f6bad9285f",
          "sha1": "a82cdc00799f41154804db61b236440ee93e89f7",
          "md5": "e8b351e6cefe4bc84969237bf082c4af"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-viewmodel-jvm-1.7.0.jar",
          "url": "precompose-viewmodel-jvm-1.7.0.jar",
          "size": 10562,
          "sha512": "d686b2eb3afe19f0c0e69475964f555a16ce06f2bb8aaf75db8d837248d26c46d106088e054c7f9d7c60e931ab45f1af55cb12579c32a378972959269845f7c3",
          "sha256": "8e175e870fe94b5c786acf46a223fea25037165cf7a71d62f7ea90f6bad9285f",
          "sha1": "a82cdc00799f41154804db61b236440ee93e89f7",
          "md5": "e8b351e6cefe4bc84969237bf082c4af"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "precompose-viewmodel-jvm-1.7.0-sources.jar",
          "url": "precompose-viewmodel-jvm-1.7.0-sources.jar",
          "size": 3135,
          "sha512": "aaae553ec322975a776b4c096de0c481fd3ab936e519482937c4d45184f6d65ba08632f4a60ec3f0f9a15bd3e763158a6b6de5c92aaa9ceb4bed70e44204fb78",
          "sha256": "f5c471443c79f7f56119b57c42d47942eebd8c72ae725d47f9511833dcdfea01",
          "sha1": "ec03f595745df665ab99e3dfeadc8c89f951d837",
          "md5": "73d4f385dcf64a6d8f6bd14b85da17b8"
        }
      ]
    }
  ]
}
