{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose-koin/1.7.0/precompose-koin-1.7.0.module",
    "group": "moe.tlaster",
    "module": "precompose-koin",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose-viewmodel",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin.klib",
          "url": "precompose-koin-macosarm64-1.7.0.klib",
          "size": 9305,
          "sha512": "6fc14c86bc6a02d8f6ecaec182c602a517b4ff5abe4652a498a98a9859a50e0bffa4dcaa913bd453a13d1fee3538f0ee54e10bcb6378942eee54f7a2465819cc",
          "sha256": "9fec6d4811d7e9acb0a3bebab7dd10ca64f836e699f363d198705c04b510572c",
          "sha1": "5965f45ea24f9a6ac8fdbff8d8b481cb0b883d79",
          "md5": "4c0710e61a64d443c363a4389f4510aa"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "precompose-koin-macosarm64-1.7.0-sources.jar",
          "url": "precompose-koin-macosarm64-1.7.0-sources.jar",
          "size": 1559,
          "sha512": "194d8e9967a4f37928679f4ac73d59a9a2f913cd8834f4f4349b05fc12f11ca76a4946ea4dea31b971ab3c7fb9cdaff86d10c983eb1d689b262ba73f7b3deba6",
          "sha256": "12dbb78fca3a1a7bb05bb06087206fa2829964d4b0b9252bf439f409c45a3e5d",
          "sha1": "70ef88a6f223a3104078dedcc81cf04ddf37ea23",
          "md5": "c43ad676a52f1676a9c2f09640b01986"
        }
      ]
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose-viewmodel",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin-1.7.0.kotlin_resources.zip",
          "url": "precompose-koin-macosarm64-1.7.0-kotlin_resources.kotlin_resources.zip",
          "size": 342,
          "sha512": "ead08c4733e2e188b4fa8f2a6108f71d5060afa6969bdbe4a9eef053f42a89152e14cd89a9b779a9a292dd52f07fd33f8c75f7a50c651b71c8537c54d60967e4",
          "sha256": "34f66870a4eab64bafc2688b48da78d99be63fb7ab69114edbf7c9470ffae3f2",
          "sha1": "721b4b3544c9631e21da888ea38a09eceb10af4d",
          "md5": "b74ab20ca804fd245d086815f80f2073"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose-viewmodel",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-koin-macosarm64-1.7.0-metadata.jar",
          "url": "precompose-koin-macosarm64-1.7.0-metadata.jar",
          "size": 261,
          "sha512": "9d13008c51947e6ea3d33330b1457aa17e279a46da83e5d5b06248605b693675ab49a7d6c60f4fc9dccfe2634047f92fc16a0be821751a729af151f84548d4c7",
          "sha256": "f3f503acfcf70e42641dbfd5f98d549766403fd7e1fc8b5456c433d36bd70c1e",
          "sha1": "12d0790230799250185cf03ec207db47165f144a",
          "md5": "6e2135f0639402ad35cc202559328a97"
        }
      ]
    }
  ]
}
