{
  "formatVersion": "1.1",
  "component": {
    "group": "moe.tlaster",
    "module": "precompose-viewmodel",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-viewmodel-metadata-1.7.0.jar",
          "url": "precompose-viewmodel-1.7.0.jar",
          "size": 4037,
          "sha512": "efd42967914601407136da88a4bd5f2bf31827443dd7e1209545dfc4898c13369f4b98efebe544fa7624fb5991521888ac9f4b604eaf5a8982819f3b9ddcb9b9",
          "sha256": "1771e4381b154bf49c6b2a5f81c8e98246bc91adaa43dafc831168b0d5f53fcc",
          "sha1": "408c9854491f8edca45694e23ad5ac387028a001",
          "md5": "519ba25009986c7fdf204541091e0f82"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "precompose-viewmodel-kotlin-1.7.0-sources.jar",
          "url": "precompose-viewmodel-1.7.0-sources.jar",
          "size": 3135,
          "sha512": "aaae553ec322975a776b4c096de0c481fd3ab936e519482937c4d45184f6d65ba08632f4a60ec3f0f9a15bd3e763158a6b6de5c92aaa9ceb4bed70e44204fb78",
          "sha256": "f5c471443c79f7f56119b57c42d47942eebd8c72ae725d47f9511833dcdfea01",
          "sha1": "ec03f595745df665ab99e3dfeadc8c89f951d837",
          "md5": "73d4f385dcf64a6d8f6bd14b85da17b8"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-android-debug/1.7.0/precompose-viewmodel-android-debug-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-android-debug",
        "version": "1.7.0"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-android-debug/1.7.0/precompose-viewmodel-android-debug-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-android-debug",
        "version": "1.7.0"
      }
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-android-debug/1.7.0/precompose-viewmodel-android-debug-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-android-debug",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-android/1.7.0/precompose-viewmodel-android-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-android/1.7.0/precompose-viewmodel-android-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-android/1.7.0/precompose-viewmodel-android-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-iosarm64/1.7.0/precompose-viewmodel-iosarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-iosarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-iosarm64/1.7.0/precompose-viewmodel-iosarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-iosarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-iosarm64/1.7.0/precompose-viewmodel-iosarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-iosarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-iosarm64/1.7.0/precompose-viewmodel-iosarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-iosarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-iossimulatorarm64/1.7.0/precompose-viewmodel-iossimulatorarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-iossimulatorarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-iossimulatorarm64/1.7.0/precompose-viewmodel-iossimulatorarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-iossimulatorarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-iossimulatorarm64/1.7.0/precompose-viewmodel-iossimulatorarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-iossimulatorarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-iossimulatorarm64/1.7.0/precompose-viewmodel-iossimulatorarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-iossimulatorarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-iosx64/1.7.0/precompose-viewmodel-iosx64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-iosx64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-iosx64/1.7.0/precompose-viewmodel-iosx64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-iosx64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-iosx64/1.7.0/precompose-viewmodel-iosx64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-iosx64",
        "version": "1.7.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-iosx64/1.7.0/precompose-viewmodel-iosx64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-iosx64",
        "version": "1.7.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-js/1.7.0/precompose-viewmodel-js-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-js",
        "version": "1.7.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-js/1.7.0/precompose-viewmodel-js-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-js",
        "version": "1.7.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-js/1.7.0/precompose-viewmodel-js-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-js",
        "version": "1.7.0"
      }
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-js/1.7.0/precompose-viewmodel-js-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-js",
        "version": "1.7.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-jvm/1.7.0/precompose-viewmodel-jvm-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-jvm",
        "version": "1.7.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-jvm/1.7.0/precompose-viewmodel-jvm-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-jvm",
        "version": "1.7.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-jvm/1.7.0/precompose-viewmodel-jvm-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-jvm",
        "version": "1.7.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-macosarm64/1.7.0/precompose-viewmodel-macosarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-macosarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-macosarm64/1.7.0/precompose-viewmodel-macosarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-macosarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-macosarm64/1.7.0/precompose-viewmodel-macosarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-macosarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-macosarm64/1.7.0/precompose-viewmodel-macosarm64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-macosarm64",
        "version": "1.7.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-macosx64/1.7.0/precompose-viewmodel-macosx64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-macosx64",
        "version": "1.7.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-macosx64/1.7.0/precompose-viewmodel-macosx64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-macosx64",
        "version": "1.7.0"
      }
    },
    {
      "name": "macosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-macosx64/1.7.0/precompose-viewmodel-macosx64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-macosx64",
        "version": "1.7.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-macosx64/1.7.0/precompose-viewmodel-macosx64-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-macosx64",
        "version": "1.7.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-wasm-js/1.7.0/precompose-viewmodel-wasm-js-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-wasm-js",
        "version": "1.7.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-wasm-js/1.7.0/precompose-viewmodel-wasm-js-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-wasm-js",
        "version": "1.7.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-wasm-js/1.7.0/precompose-viewmodel-wasm-js-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-wasm-js",
        "version": "1.7.0"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../precompose-viewmodel-wasm-js/1.7.0/precompose-viewmodel-wasm-js-1.7.0.module",
        "group": "moe.tlaster",
        "module": "precompose-viewmodel-wasm-js",
        "version": "1.7.0"
      }
    }
  ]
}
