{
  "formatVersion": "1.1",
  "component": {
    "url": "../../precompose-viewmodel/1.7.0/precompose-viewmodel-1.7.0.module",
    "group": "moe.tlaster",
    "module": "precompose-viewmodel",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-viewmodel-js-1.7.0.klib",
          "url": "precompose-viewmodel-js-1.7.0.klib",
          "size": 3325884,
          "sha512": "9a55d95cd12568ec1451b1979742e5ac0b7e2e8e75f5d1deded6b7624c2815a6154047a1c176e6c0184ca406e8e36f2942be87f5c4e70dbffa29c3e2cf12878f",
          "sha256": "3338d493a9bf2abb4d48c9eac340218b127b909d3cf83e1beb13ec050e472bb1",
          "sha1": "2db6e6fd5b4f48ef9e956bb4759959b9ee52bbd5",
          "md5": "b90d627ea62567e2eeefb198313f1ba8"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-viewmodel-js-1.7.0.klib",
          "url": "precompose-viewmodel-js-1.7.0.klib",
          "size": 3325884,
          "sha512": "9a55d95cd12568ec1451b1979742e5ac0b7e2e8e75f5d1deded6b7624c2815a6154047a1c176e6c0184ca406e8e36f2942be87f5c4e70dbffa29c3e2cf12878f",
          "sha256": "3338d493a9bf2abb4d48c9eac340218b127b909d3cf83e1beb13ec050e472bb1",
          "sha1": "2db6e6fd5b4f48ef9e956bb4759959b9ee52bbd5",
          "md5": "b90d627ea62567e2eeefb198313f1ba8"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "precompose-viewmodel-js-1.7.0-sources.jar",
          "url": "precompose-viewmodel-js-1.7.0-sources.jar",
          "size": 3135,
          "sha512": "aaae553ec322975a776b4c096de0c481fd3ab936e519482937c4d45184f6d65ba08632f4a60ec3f0f9a15bd3e763158a6b6de5c92aaa9ceb4bed70e44204fb78",
          "sha256": "f5c471443c79f7f56119b57c42d47942eebd8c72ae725d47f9511833dcdfea01",
          "sha1": "ec03f595745df665ab99e3dfeadc8c89f951d837",
          "md5": "73d4f385dcf64a6d8f6bd14b85da17b8"
        }
      ]
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "moe.tlaster",
          "module": "precompose",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "precompose-viewmodel-1.7.0.kotlin_resources.zip",
          "url": "precompose-viewmodel-js-1.7.0-kotlin_resources.kotlin_resources.zip",
          "size": 352,
          "sha512": "d7ee2e10e6243c4098f28a8b2675066498feb27acb416b8884c08e1fdf07922a19d8a2b5200df627959c45f9fb58ee9bec5e26c388871081263fb2730a734fa0",
          "sha256": "9f495d67dd83e9d8044ef1fd5c5949087e0ef271aa0eabd81d76b9e65c1083d3",
          "sha1": "b51f9f548f35c4cfa21cec4d427b6c32e7325d22",
          "md5": "f0d171b4852f468051c88fc84b9f5f2d"
        }
      ]
    }
  ]
}
